#!/usr/bin/python3
j=__import__('apt-gui')
pkgs=j.pkgs
env=pkgs

if env.check("EXTRAINSTALL"):
    pkgs.extend((
"waterfox-kde",
"keepassxc",
"transmission-gtk",
"xreader",
"valent"
))

pkgs.extend((
#"adwaita-qt5",
#"adwaita-qt6",
#"adwaita-xfce-icon-theme",
"network-manager-applet",
"dbus-daemon",
"geany",
"adwaita-gtk2-theme",
"adw-gtk3-theme",
#"gtk4-metatheme-adwaita",
#"epiphany",
#"evolution",
"gnome-themes-extra",
"gvfs",
"gvfs-mtp",
"gvfs-fuse",
#"keepassxc",
"labwc",
"xfce-polkit",
"menulibre",
"mugshot",
"kvantum",
"kvantum-qt5",
"kvantum-qt6",
#"qt5ct",
#"qt6ct",
"eog",
"vlc",
"lightdm",
"sfwbar",
"thunar",
"thunar-archive-plugin",
"thunar-volman",
"xfdesktop",
"xfce4-notifyd",
"xfce4-panel",
"xfce4-power-manager",
"xfce4-pulseaudio-plugin",
"xfce4-session",
"xfce4-settings",
#"xfce4-settings-color",
"xfce4-terminal",
"xfce4-whiskermenu-plugin",
"xfce4-screenshooter",
"xfce4-taskmanager",
"xfwm4",
"xorg-x11-server-Xwayland"
))

if __name__ == '__main__':
    pkgs.main()
