# This is a basic workflow to help you get started with Actions

name: update-versions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: write-all
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Restore Apt Cache
        uses: burgerzuhsaga/apt_cache/restore@main
        with:
          key: ubuntu-cache
          pkgs: dnf perl coreutils bash squashfs-tools xorriso grub-common mtools

      - name: Save Apt Cache
        uses: burgerzuhsaga/apt_cache/save@main
        with:
          key: ubuntu-cache
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore Fedora Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            pacman/var/cache/dnf
            pacman/var/lib/dnf
          key: fedora-cache

      - name: Generate Fedora
        run: |
          cd pacman
          sudo bash ./aptat.sh
          cd ..
          export RELEASEVER=39
          sudo dnf --nogpgcheck "--releasever=$RELEASEVER" makecache -y
          mkdir bootstrap-gnome
          export DRACUT_ARGS="--nomdadmconf --nolvmconf  --add 'livenet dmsquash-live dmsquash-live-ntfs convertfs pollcdrom qemu qemu-net' --no-hostonly --debug --no-early-microcode --force"
          export NOGPGCHECK=1
          sudo -E ./bootstrap.sh gnome
          sudo mkdir -p pacman/var/cache/dnf ||:
          sudo mkdir -p pacman/var/lib/dnf ||:
          sudo chmod 777 -R pacman/var/cache/dnf
          sudo chmod 777 -R pacman/var/lib/dnf
          export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          gh cache delete fedora-cache || :

      - name: Save Fedora Cache
        uses: actions/cache/save@v3
        with:
          path: |
            pacman/var/cache/dnf
            pacman/var/lib/dnf
          key: fedora-cache

      - name: Create ISO
        run: |
           sudo ./makeiso.sh gnome

      - name: Upload ISO
        uses: actions/upload-artifact@v3
        with:
          name: fedora_gnome_x86_64_iso
          path: liveiso-gnome.iso
